### ISSUE TITLE
npm run build occur error.

### ISSUE THREAD

**Issue by 1242132039** [sz-cloudata/clouddata-survey-web#1]
> gulp build

module.js:327
    throw err;
    ^

Error: Cannot find module 'lodash.template'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/fechow/clouddata-survey-web/node_modules/gulp-util/lib/template.js:1:78)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

**Comment by 1242132039** [comment]
rm -rf node_modules && npm cache clean && npm i gulp && npm i -g gulp-cli
